apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: wiki
  POSTGRES_USER: wikijs
  POSTGRES_PASSWORD: "123123"
  POSTGRES_HOST_AUTH_METHOD: trust
