apiVersion: v1
kind: Service
metadata:
  name: wiki
spec:
  type: NodePort
  selector:
    app: wiki
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000 #exported to cluster
      targetPort: 8000 #used to send requests to the pod
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007 #exported to the "outside"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  labels:
    app: wiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: requarks/wiki:2
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: wikijs
        - name: DB_PASS
          value: wikijsrocks
        - name: DB_NAME
          value: wiki
        ports:
        - containerPort: 8000
          name: wiki
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: swap