apiVersion: v1
kind: Service
metadata:
  name: wikijs-nodeport
spec:
  type: NodePort
  selector:
    app: wikijs
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80 #exported to cluster
      targetPort: 8000 #used to send requests to the pod
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008 #exported to the "outside"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs-nodeport
  labels:
    app: wikijs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs-nodeport
        image: requarks/wiki:2
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_TYPE
          value: postgres
        - name: DB_USER
          value: wiki
        - name: DB_PORT
          value: "5432"
        - name: DB_PASS
          value: "123123"
        - name: DB_NAME
          value: wiki
        ports:
        - containerPort: 8000
          name: wikijs-nodeport
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: swap
