---

- name: Reset kubernetes and remove old files
  command: "{{ item }}"
  with_items:
    - kubeadm reset --force
    - rm -rf /etc/cni/net.d
    - rm -rf "{{ home }}"/.kube/config

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh

# - name: Remove cni0 device
#   command: "{{ item }}"
#   with_items:
#     - ip link set cni0 down
#     - ip link delete cni0