---

# - name: dpkg configure
#   command: dpkg --configure -a

- name: Update system packages
  apt:
          update_cache: yes
          force_apt_get: yes
          dpkg_options: "force-confdef,force-confold"
          upgrade: dist


- name: Install packages
  apt:
          name: "{{ item }}"
          force_apt_get: yes
          install_recommends: yes
          state: latest
  loop: "{{ common_packages }}"


- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ common_packages_https }}"

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: remove docker
  apt: name=docker.io state=absent

- name: Install docker and its dependencies
  apt: 
    update_cache: yes
    name: docker.io
    state: present

# - name: Restart docker
#   service:
#     name: docker
#     state: started
#     enabled: yes
#   notify: restart docker

- name: start docker
  service: 
    name: docker 
    state: started

- name: Change daemon.json
  #shell: echo "{"exec-opts": ["native.cgroupdriver=systemd"]}" >> /etc/docker/daemon.json
  lineinfile:
      path: /etc/docker/daemon.json
      line: '{"exec-opts": ["native.cgroupdriver=systemd"]}'
      create: yes

# - name: Add user to docker group
#   user:
#       name: joaopereira
#       group: docker

# Install kubernetes
- name: Remove swap file
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items: "{{ swap_items }}"

- name: Reset kubernetes and remove old files
  command: "{{ item }}"
  with_items:
    - kubeadm reset --force
    - rm -rf /etc/cni/net.d
    - rm -rf "{{ home }}"/.kube/config
  args:
    warn: false

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ kubernetes_packages }}"

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted