#[master]
#10.128.0.2

#[wiki]
#10.128.0.3

#[wiki-db]
#10.128.0.5

#[workers]
#10.128.0.3
#10.128.0.5

all:
  children:
    master:
      hosts:
        10.128.0.9:
    worker:
      children:
        wiki:
          hosts:
            10.128.0.10:
        wiki_db:
          hosts:
            10.128.0.11:


#[master:vars]
#ansible_ssh_common_args="-o StrictHostKeyChecking=no"

#[wiki:vars]
#ansible_ssh_common_args="-o StrictHostKeyChecking=no"

#[wiki-db:vars]
#ansible_ssh_common_args="-o StrictHostKeyChecking=no"
