---

- name: Basic VMs configuration
  hosts: all
  become: yes
  roles: 
    - common

- name: Master tasks
  hosts: master
  become: yes
  roles:
    - master

- name: Workers tasks
  hosts: worker
  become: yes
  roles:
    - worker

# - name: Deploy wikijs database in VM4
#   hosts: wiki_db
#   become: yes
#   roles:
#     - wiki_db

# - name: Deploy wikijs in VM2
#   hosts: wiki
#   roles:
#     - wiki
                        

