---

- name: Basic VMs configuration
  hosts: all
  become: yes
  roles: 
    - common

# - name: Deploy wikijs database in VM3
#   hosts: wiki-db
#   become: yes
#   roles:
#     - db

# - name: Deploy wikijs in VM2
#   hosts: wiki
#   roles:
#     - wiki
                        

